### ISSUE TITLE
训练结果问题

### ISSUE THREAD

**Issue by zhoumenghan** [xlang-ai/aguvis#3]
您好，目前仅用了您在huggine face上公开的webUI和omniAct数据集，进行训练，推理结果如下：
![image](https://github.com/user-attachments/assets/c6c2ffd5-c542-4c2e-9061-0e2b25646932)

可以看到输出格式不太统一，我目前在screenspot上评估只能匹配第一个括号内的数值，但有时output会有好几个括号，且里面数值不一样，请问这正常吗？
![image](https://github.com/user-attachments/assets/9c2bb017-cf86-4972-873e-b0ab493506dc)

我目前的推理相关代码如下，还请您指点是否正确：

        messages = [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "image": f"{img_path}",
                    },
                    {"type": "text",
                     "text": f"\"{instruction}\""},
                ],
            }
        ]

        # Preparation for inference
        text = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        image_inputs, video_inputs = process_vision_info(messages)
        inputs = processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        )
        inputs = inputs.to("cuda")

        # Inference: Generation of the output
        generated_ids = model.generate(**inputs, max_new_tokens=128)

        generated_ids_trimmed = [
            out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]

        output_text = processor.batch_decode(
            generated_ids_trimmed, skip_special_tokens=False, clean_up_tokenization_spaces=False
        )

        print("output_text: ", output_text)

**Comment by easonyang1996** [comment]
@zhoumenghan hi, Met same problem as yours! I think the output is redundant. For ScreenSpot, one grounded action is enough for each instruction. But my stage1 model generates multiple grounded actions or lots of meaningless tokens like "assistant"\"assistantos".
`pyautogui.click(x=0.9698, y=0.1532)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.2148)
assistant
assistantos
pyautogui.click(x=0.9878, y=0.`

**Comment by kugwzk** [comment]
Hi, thank you for your feedback!

Before the model inference, please verify the following configurations in the model checkpoint directory:

1. **Update `eos_token_id`:**
   - Set the `eos_token_id` to `151658` in both `config.json` and `generation_config.json`.

2. **Modify `eos_token`:**
   - Change the `eos_token` from `<im_end>` to `<diff_marker>` in `tokenizer_config.json`.

**Comment by DAAworld** [comment]
训练大约会消耗多少显存呢？

**Comment by zhoumenghan** [comment]
感谢大佬！

**Comment by hj611** [comment]
Can you share your training script please？thank you！

**Comment by hj611** [comment]
请问可以分享你的测试脚本吗，我在作者全量一阶段数据上训练后，在screenspot上评估点数很低（只有十几），非常感谢！

**Comment by hj611** [comment]
> 您好，目前仅用了您在huggine face上公开的webUI和omniAct数据集，进行训练，推理结果如下： ![image](https://private-user-images.githubusercontent.com/30396038/398556217-c6c2ffd5-c542-4c2e-9061-0e2b25646932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2MTAxMzksIm5iZiI6MTczNjYwOTgzOSwicGF0aCI6Ii8zMDM5NjAzOC8zOTg1NTYyMTctYzZjMmZmZDUtYzU0Mi00YzJlLTkwNjEtMGUyYjI1NjQ2OTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTExVDE1MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZjI5MjU4NWY0NmI4NzMwODk3YTQwZmYxZGIyMTYyMmFlZmJkMmMwYjA4YTllODgxMmMwN2JjNDhmYmZiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6dbwUUMCj1zXAXCBHvdYNfpEIUiYbsCUZrR_a_xnwdo)
> 
> 可以看到输出格式不太统一，我目前在screenspot上评估只能匹配第一个括号内的数值，但有时output会有好几个括号，且里面数值不一样，请问这正常吗？ ![image](https://private-user-images.githubusercontent.com/30396038/398556277-9c2bb017-cf86-4972-873e-b0ab493506dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2MTAxMzksIm5iZiI6MTczNjYwOTgzOSwicGF0aCI6Ii8zMDM5NjAzOC8zOTg1NTYyNzctOWMyYmIwMTctY2Y4Ni00OTcyLTg3M2UtYjBhYjQ5MzUwNmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTExVDE1MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MmI1YzFhMWI4NzdkNzg2Y2E5Y2E2ZDJjZjcxMTc0MjY0NzRhNDNmMTU3NzljMzQ2NGEyYjYzNDczYmEyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bU0Xz4FhaRHrLBBqMwJtxZJCy9euqhv6RRLO4E6KgQE)
> 
> 我目前的推理相关代码如下，还请您指点是否正确：
> 
> ```
>     messages = [
>         {
>             "role": "user",
>             "content": [
>                 {
>                     "type": "image",
>                     "image": f"{img_path}",
>                 },
>                 {"type": "text",
>                  "text": f"\"{instruction}\""},
>             ],
>         }
>     ]
> 
>     # Preparation for inference
>     text = processor.apply_chat_template(
>         messages, tokenize=False, add_generation_prompt=True
>     )
>     image_inputs, video_inputs = process_vision_info(messages)
>     inputs = processor(
>         text=[text],
>         images=image_inputs,
>         videos=video_inputs,
>         padding=True,
>         return_tensors="pt",
>     )
>     inputs = inputs.to("cuda")
> 
>     # Inference: Generation of the output
>     generated_ids = model.generate(**inputs, max_new_tokens=128)
> 
>     generated_ids_trimmed = [
>         out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
>     ]
> 
>     output_text = processor.batch_decode(
>         generated_ids_trimmed, skip_special_tokens=False, clean_up_tokenization_spaces=False
>     )
> 
>     print("output_text: ", output_text)
> ```

请问可以分享你的测试脚本吗，我在作者全量一阶段数据上训练后，在screenspot上评估点数很低（只有十几），非常感谢！

**Comment by Gmrylbx** [comment]
> Hi, thank you for your feedback!
> 
> Before the model inference, please verify the following configurations in the model checkpoint directory:
> 
> 1. **Update `eos_token_id`:**
>    
>    * Set the `eos_token_id` to `151658` in both `config.json` and `generation_config.json`.
> 2. **Modify `eos_token`:**
>    
>    * Change the `eos_token` from `<im_end>` to `<diff_marker>` in `tokenizer_config.json`.

但是，我换成qwen2.5vl，使用aguvis的代码训练stage1，checkpoint里面 `config.json` 和 `generation_config.json` 的原本的eos_token_id=[151666]，这种情况下是可以输出正常的结果的，但当我按照这个issue的方法换成[151658]，反而会输出很长一段结果，而且推理时长增加了十倍，这是因为你们已经进行了修复是吗？
